# Generated by Django 5.2 on 2025-05-05 07:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SearchQuery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('search_term', models.CharField(db_index=True, max_length=255, unique=True)),
                ('max_page_scraped', models.PositiveIntegerField(default=0)),
                ('last_updated', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('page', models.PositiveIntegerField()),
                ('title', models.CharField(max_length=500)),
                ('price', models.CharField(max_length=100)),
                ('seller', models.CharField(blank=True, max_length=255, null=True)),
                ('reviews', models.CharField(blank=True, max_length=255, null=True)),
                ('image_url', models.URLField(blank=True, max_length=2048, null=True)),
                ('scraped_at', models.DateTimeField(auto_now_add=True)),
                ('search_query', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to='api.searchquery')),
            ],
            options={
                'ordering': ['scraped_at'],
                'unique_together': {('search_query', 'page', 'title', 'image_url')},
            },
        ),
    ]
